version: "3"

services:
  redis:
    build:
      context: .docker/redis
      dockerfile: Dockerfile
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data

  commander:
    image: rediscommander/redis-commander
    ports:
      - 8081:8081
    environment:
      - REDIS_HOSTS=local:redis:6379:0:password
